"""05_edit_many_to_many_depend_by_lazy_dynamic

Revision ID: 0077dec0fcda
Revises: 16c615f6b341
Create Date: 2023-03-02 15:31:55.748616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0077dec0fcda'
down_revision = '16c615f6b341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
