"""05_edit_many_to_many_dependies

Revision ID: 16c615f6b341
Revises: 76a78e0b20c2
Create Date: 2023-03-02 14:37:45.324139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c615f6b341'
down_revision = '76a78e0b20c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
