"""12_edit_many_to_many_dependies_for_platforms

Revision ID: 17d60819c8a1
Revises: 4d7ffa488c5a
Create Date: 2023-03-22 13:26:05.246250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d60819c8a1'
down_revision = '4d7ffa488c5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_platform_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('games_platform_id_fkey', 'games', 'platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###
