"""11_edit_many_to_many_dependies_for_platforms

Revision ID: 4d7ffa488c5a
Revises: 88d86d33dd12
Create Date: 2023-03-22 13:24:38.809894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7ffa488c5a'
down_revision = '88d86d33dd12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
