"""04_edit_genre_games_field

Revision ID: 76a78e0b20c2
Revises: 830abaa5abf4
Create Date: 2023-02-21 17:59:33.054329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a78e0b20c2'
down_revision = '830abaa5abf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
