"""06_edit_one_to_one_depend_on_platform

Revision ID: 7b596d5e8265
Revises: 0077dec0fcda
Create Date: 2023-03-02 15:33:22.673017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b596d5e8265'
down_revision = '0077dec0fcda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
