"""02_roles

Revision ID: 7fd345342aea
Revises: e780d6b6ff59
Create Date: 2023-01-30 15:29:37.413848

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.models.enums import UserRoles


# revision identifiers, used by Alembic.
revision = '7fd345342aea'
down_revision = 'e780d6b6ff59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(
            choices=UserRoles,
            impl=(sa.Integer())), nullable=True
                  )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
