"""03_edit_genre_games_field

Revision ID: 830abaa5abf4
Revises: d3ac69abbe3b
Create Date: 2023-02-21 17:45:53.611994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830abaa5abf4'
down_revision = 'd3ac69abbe3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
