"""13_edit_many_to_many_dependies_for_platforms

Revision ID: 969b5dfdc97e
Revises: 17d60819c8a1
Create Date: 2023-03-22 13:26:39.857083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969b5dfdc97e'
down_revision = '17d60819c8a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
