"""07_edit_one_to_one_depend_on_platform

Revision ID: b4725b46bbff
Revises: 7b596d5e8265
Create Date: 2023-03-02 15:34:29.343532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4725b46bbff'
down_revision = '7b596d5e8265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
