"""03_roles

Revision ID: b911f43b633e
Revises: 7fd345342aea
Create Date: 2023-01-31 14:29:31.244341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b911f43b633e'
down_revision = '7fd345342aea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
