"""04_roles

Revision ID: c0e2ad1b2566
Revises: b911f43b633e
Create Date: 2023-01-31 14:32:55.297666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e2ad1b2566'
down_revision = 'b911f43b633e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
