"""08_edit_many_to_many_dependies

Revision ID: ccd9c8f552ca
Revises: b4725b46bbff
Create Date: 2023-03-02 15:40:11.227485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd9c8f552ca'
down_revision = 'b4725b46bbff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
