"""02_edit_genre_games_field

Revision ID: d3ac69abbe3b
Revises: a3f3c396221e
Create Date: 2023-02-21 17:34:02.711674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ac69abbe3b'
down_revision = 'a3f3c396221e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
